### ISSUE TITLE
Could not open database environment; please check options and file system

### ISSUE THREAD

**Issue by ihbing** [objectbox/objectbox-c#12]
**Describe the bug**
 Could not create ObjectBox - please check configuration: Could not open database environment; please check options and file system (13) [recovered]

**Basic info (please complete the following information):**
 - ObjectBox version: [latest version]
 - C or C++ version: [unknown]
 - Reproducibility: [always]
 - OS: [Window10]

**To Reproduce**
go test

**Expected behavior**

**Code**
**Logs, stack traces**
```
panic: Could not create ObjectBox - please check configuration: Could not open database environment; please check options and file system (13) [recovered]
        panic: Could not create ObjectBox - please check configuration: Could not open database environment; please check options and file system (13)

goroutine 51 [running]:
testing.tRunner.func1(0xc00012e700)
        /usr/lib/go-1.13/src/testing/testing.go:874 +0x3a3
panic(0x665820, 0xc000200540)
        /usr/lib/go-1.13/src/runtime/panic.go:679 +0x1b2
github.com/objectbox/objectbox-go/objectbox.(*Builder).Build(0xc00021c4c0, 0xc0002047e0, 0xc00021c4c0, 0x0)
        /home/ihbing/go/pkg/mod/github.com/objectbox/objectbox-go@v1.2.0/objectbox/builder.go:133 +0xdc
souobjectboxparser/objectboxparser.initObjectBox(0xc00012b600, 0x12, 0xc000220000)
        /mnt/f/task/soul/src/souobjectboxparser/objectboxparser/objectboxparser.go:66 +0xa6
souobjectboxparser/objectboxparser.ParseMDBData(0xc000220000, 0x1d000, 0x1d200, 0x0, 0x0)
        /mnt/f/task/soul/src/souobjectboxparser/objectboxparser/objectboxparser.go:34 +0x158
souobjectboxparser/objectboxparser.Start()
        /mnt/f/task/soul/src/souobjectboxparser/objectboxparser/objectboxparser.go:17 +0xc5
souobjectboxparser/objectboxparser.TestStart(0xc00012e700)
        /mnt/f/task/soul/src/souobjectboxparser/objectboxparser/objectboxparser_test.go:6 +0x20
testing.tRunner(0xc00012e700, 0x6e7ee0)
        /usr/lib/go-1.13/src/testing/testing.go:909 +0xc9
created by testing.(*T).Run
        /usr/lib/go-1.13/src/testing/testing.go:960 +0x350
exit status 2

```

**Additional context**

**Comment by ihbing** [comment]
Problem found: "data.mdb" file permission read-only mode.
